# kubectl create secret generic mysql-pass --from-literal=password=redhat 
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  password: c2FtZWVya2hhbg==  # Base64 encoded value
